In [1]:
import pandas as pd

In [2]:
inventory = pd.read_csv('O:/Northwood/Capstone/bookstore_datasets/bookstore_inventory.csv')
inventory.head()

,month,from,to,sku,qty,unit_cost,unit_price,extended_cost,extended_retail,dataset
0,2019-01-01,YYC-WH,YYC-DT,BK1000,19,8.09,18.92,153.71,359.48,bookstore_inventory
1,2019-01-01,YYC-WH,YYC-NW,BK1000,10,8.09,18.92,80.90,189.20,bookstore_inventory
2,2019-01-01,YYC-WH,YYC-SE,BK1000,7,8.09,18.92,56.63,132.44,bookstore_inventory
3,2019-01-01,YYC-WH,YYC-DT,BK1001,21,10.75,24.49,225.75,514.29,bookstore_inventory
4,2019-01-01,YYC-WH,YYC-NW,BK1001,13,10.75,24.49,139.75,318.37,bookstore_inventory

In [69]:
sales_data = pd.read_csv('O:/Northwood/Capstone/bookstore_datasets/bookstore_sales.csv')
sales_data.head(10)

,date,year,month,store_id,channel,transactions,revenue,gst_collected,net_revenue,dataset
0,2019-01-01,2019,1,YYC-DT,IN_STORE,64,1985.46,99.27,1886.19,bookstore_sales
1,2019-01-01,2019,1,YYC-DT,ONLINE,8,207.72,10.39,197.33,bookstore_sales
2,2019-01-01,2019,1,YYC-NW,IN_STORE,49,1466.95,73.35,1393.60,bookstore_sales
3,2019-01-01,2019,1,YYC-NW,ONLINE,4,148.89,7.44,141.45,bookstore_sales
4,2019-01-01,2019,1,YYC-SE,IN_STORE,33,1272.70,63.64,1209.06,bookstore_sales
5,2019-01-01,2019,1,YYC-SE,ONLINE,4,96.35,4.82,91.53,bookstore_sales
6,2019-01-02,2019,1,YYC-DT,IN_STORE,53,1965.86,98.29,1867.57,bookstore_sales
7,2019-01-02,2019,1,YYC-DT,ONLINE,9,227.74,11.39,216.35,bookstore_sales
8,2019-01-02,2019,1,YYC-NW,IN_STORE,34,1501.10,75.05,1426.05,bookstore_sales
9,2019-01-02,2019,1,YYC-NW,ONLINE,4,125.14,6.26,118.88,bookstore_sales

In [4]:
print(inventory.shape)
print(sales_data.shape)

(21566, 10)
(13152, 10)

In [5]:
inventory.describe()

,qty,unit_cost,unit_price,extended_cost,extended_retail
count,21566.000000,21566.000000,21566.000000,21566.000000,21566.000000
mean,13.607020,12.380085,26.323480,168.395885,358.156324
std,6.483232,3.528916,7.857572,95.771328,206.848009
min,1.000000,6.080000,11.510000,6.270000,11.510000
25%,9.000000,9.120000,18.920000,98.100000,205.380000
50%,13.000000,13.110000,27.050000,150.100000,320.400000
75%,17.000000,15.360000,31.930000,219.167500,467.210000
max,52.000000,17.770000,42.690000,703.560000,1664.910000

In [6]:
sales_data.describe()

,year,month,transactions,revenue,gst_collected,net_revenue
count,13152.000000,13152.000000,13152.000000,13152.000000,13152.000000,13152.000000
mean,2021.500456,6.521898,32.601125,1051.288171,52.564473,998.723698
std,1.708246,3.449117,24.465208,762.231707,38.111537,724.120169
min,2019.000000,1.000000,3.000000,83.830000,4.190000,79.640000
25%,2020.000000,4.000000,12.000000,409.035000,20.450000,388.585000
50%,2021.500000,7.000000,24.000000,780.325000,39.020000,741.305000
75%,2023.000000,10.000000,49.000000,1586.855000,79.342500,1507.512500
max,2024.000000,12.000000,154.000000,4279.490000,213.970000,4065.520000

In [7]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13152 entries, 0 to 13151
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           13152 non-null  object
 1   year           13152 non-null  int64
 2   month          13152 non-null  int64
 3   store_id       13152 non-null  object
 4   channel        13152 non-null  object
 5   transactions   13152 non-null  int64
 6   revenue        13152 non-null  float64
 7   gst_collected  13152 non-null  float64
 8   net_revenue    13152 non-null  float64
 9   dataset        13152 non-null  object
dtypes: float64(3), int64(3), object(4)
memory usage: 1.0+ MB

In [8]:
inventory.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21566 entries, 0 to 21565
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   month            21566 non-null  object
 1   from             21566 non-null  object
 2   to               21566 non-null  object
 3   sku              21566 non-null  object
 4   qty              21566 non-null  int64
 5   unit_cost        21566 non-null  float64
 6   unit_price       21566 non-null  float64
 7   extended_cost    21566 non-null  float64
 8   extended_retail  21566 non-null  float64
 9   dataset          21566 non-null  object
dtypes: float64(4), int64(1), object(5)
memory usage: 1.6+ MB

In [9]:
print(sales_data.dtypes)

date              object
year               int64
month              int64
store_id          object
channel           object
transactions       int64
revenue          float64
gst_collected    float64
net_revenue      float64
dataset           object
dtype: object

In [10]:
sales_data['date'] = pd.to_datetime(sales_data['date'], format = "%Y-%m-%d")
print(sales_data.dtypes)

date             datetime64[ns]
year                      int64
month                     int64
store_id                 object
channel                  object
transactions              int64
revenue                 float64
gst_collected           float64
net_revenue             float64
dataset                  object
dtype: object

In [11]:
sales_data["date"] = sales_data["date"].dt.to_period("M")

In [12]:
sales_data.head()

,date,year,month,store_id,channel,transactions,revenue,gst_collected,net_revenue,dataset
0,2019-01,2019,1,YYC-DT,IN_STORE,64,1985.46,99.27,1886.19,bookstore_sales
1,2019-01,2019,1,YYC-DT,ONLINE,8,207.72,10.39,197.33,bookstore_sales
2,2019-01,2019,1,YYC-NW,IN_STORE,49,1466.95,73.35,1393.60,bookstore_sales
3,2019-01,2019,1,YYC-NW,ONLINE,4,148.89,7.44,141.45,bookstore_sales
4,2019-01,2019,1,YYC-SE,IN_STORE,33,1272.70,63.64,1209.06,bookstore_sales

In [13]:
new_sales = sales_data [["date", 'store_id', 'transactions', 'revenue', 'gst_collected', 'net_revenue']]
print(new_sales)

          date store_id  transactions  revenue  gst_collected  net_revenue
0      2019-01   YYC-DT            64  1985.46          99.27      1886.19
1      2019-01   YYC-DT             8   207.72          10.39       197.33
2      2019-01   YYC-NW            49  1466.95          73.35      1393.60
3      2019-01   YYC-NW             4   148.89           7.44       141.45
4      2019-01   YYC-SE            33  1272.70          63.64      1209.06
...        ...      ...           ...      ...            ...          ...
13147  2024-12   YYC-DT            16   651.08          32.55       618.53
13148  2024-12   YYC-NW            90  2489.90         124.50      2365.40
13149  2024-12   YYC-NW            18   507.71          25.39       482.32
13150  2024-12   YYC-SE            85  2191.54         109.58      2081.96
13151  2024-12   YYC-SE            10   370.54          18.53       352.01

[13152 rows x 6 columns]

In [14]:
print(inventory.columns)

Index(['month', 'from', 'to', 'sku', 'qty', 'unit_cost', 'unit_price',
       'extended_cost', 'extended_retail', 'dataset'],
      dtype='object')

In [15]:
inventory.rename(columns={'month': 'year_month', 'from': 'warehouse','to':'Store_ID',
                          'extended_cost' : 'total_cost', 'extended_retail':'total_retail'}, inplace=True)

In [16]:
new_inventory = inventory [['year_month', 'warehouse','Store_ID','qty',
                           'unit_cost', 'unit_price','total_cost','total_retail']]

In [17]:
print(new_inventory.columns)

Index(['year_month', 'warehouse', 'Store_ID', 'qty', 'unit_cost', 'unit_price',
       'total_cost', 'total_retail'],
      dtype='object')

In [18]:
new_inventory['year_month'] = pd.to_datetime(new_inventory['year_month'], format = "%Y-%m-%d")

C:\Users\TempPC\AppData\Local\Temp\ipykernel_148268\2565497492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_inventory['year_month'] = pd.to_datetime(new_inventory['year_month'], format = "%Y-%m-%d")

In [19]:
new_inventory = inventory.rename(columns = {'month': 'year_month',
                                            'from': 'warehouse',
                                            'to': 'Store_ID',
                                            'extended_cost': 'total_cost',
                                            'extended_retail': 'total_retail'
                                            })[['year_month', 'warehouse', 'Store_ID','qty',
                                                'unit_cost','unit_price','total_cost','total_retail']].copy()

In [20]:
new_inventory['year_month'] = pd.to_datetime(new_inventory['year_month'])
new_inventory['year_month'] = new_inventory['year_month'].dt.to_period('M')

In [21]:
print(new_inventory.dtypes)
print(new_sales.dtypes)

year_month      period[M]
warehouse          object
Store_ID           object
qty                 int64
unit_cost         float64
unit_price        float64
total_cost        float64
total_retail      float64
dtype: object
date             period[M]
store_id            object
transactions         int64
revenue            float64
gst_collected      float64
net_revenue        float64
dtype: object

In [22]:
mydata = pd.merge(new_sales, new_inventory, left_on =['date', 'store_id'], 
                  right_on=['year_month', 'Store_ID'], how='left')

In [23]:
mydata = mydata[['date','store_id', 'warehouse','transactions','revenue', 'net_revenue',
                 'qty', 'unit_cost', 'unit_price', 'total_cost', 'total_retail']]
mydata.tail()

,date,store_id,warehouse,transactions,revenue,net_revenue,qty,unit_cost,unit_price,total_cost,total_retail
1313127,2024-12,YYC-SE,YYC-WH,10,370.54,352.01,20,15.10,27.51,302.00,550.20
1313128,2024-12,YYC-SE,YYC-WH,10,370.54,352.01,15,6.30,15.47,94.50,232.05
1313129,2024-12,YYC-SE,YYC-WH,10,370.54,352.01,22,6.27,11.51,137.94,253.22
1313130,2024-12,YYC-SE,YYC-WH,10,370.54,352.01,10,9.88,21.53,98.80,215.30
1313131,2024-12,YYC-SE,YYC-WH,10,370.54,352.01,17,11.86,27.23,201.62,462.91

In [24]:
mydata.set_index('date', inplace=True)
mydata.sort_index(inplace=True)

In [61]:
filter_mydata = mydata.loc['2021':'2024']
filter_mydata.head()

,store_id,warehouse,transactions,revenue,net_revenue,qty,unit_cost,unit_price,total_cost,total_retail
date,,,,,,,,,,
2021-01,YYC-DT,YYC-WH,31,1212.47,1151.85,20,8.09,18.92,161.8,378.40
2021-01,YYC-DT,YYC-WH,31,1212.47,1151.85,14,10.75,24.49,150.5,342.86
2021-01,YYC-DT,YYC-WH,31,1212.47,1151.85,16,15.10,31.89,241.6,510.24
2021-01,YYC-DT,YYC-WH,31,1212.47,1151.85,18,14.35,28.58,258.3,514.44
2021-01,YYC-DT,YYC-WH,31,1212.47,1151.85,10,7.85,19.61,78.5,196.10

In [26]:
filter_mydata.info()

<class 'pandas.core.frame.DataFrame'>
PeriodIndex: 874892 entries, 2021-01 to 2024-12
Freq: M
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   store_id      874892 non-null  object
 1   warehouse     874892 non-null  object
 2   transactions  874892 non-null  int64
 3   revenue       874892 non-null  float64
 4   net_revenue   874892 non-null  float64
 5   qty           874892 non-null  int64
 6   unit_cost     874892 non-null  float64
 7   unit_price    874892 non-null  float64
 8   total_cost    874892 non-null  float64
 9   total_retail  874892 non-null  float64
dtypes: float64(6), int64(2), object(2)
memory usage: 73.4+ MB

In [27]:
filter_mydata.to_csv('filtered_mydata.csv', index=True)

In [64]:
filter_mydata.groupby(['store_id']).head()

,store_id,warehouse,transactions,revenue,net_revenue,qty,unit_cost,unit_price,total_cost,total_retail
date,,,,,,,,,,
2021-01,YYC-DT,YYC-WH,31,1212.47,1151.85,20,8.09,18.92,161.80,378.40
2021-01,YYC-DT,YYC-WH,31,1212.47,1151.85,14,10.75,24.49,150.50,342.86
2021-01,YYC-DT,YYC-WH,31,1212.47,1151.85,16,15.10,31.89,241.60,510.24
2021-01,YYC-DT,YYC-WH,31,1212.47,1151.85,18,14.35,28.58,258.30,514.44
2021-01,YYC-DT,YYC-WH,31,1212.47,1151.85,10,7.85,19.61,78.50,196.10
2021-01,YYC-NW,YYC-WH,24,881.49,837.42,10,8.09,18.92,80.90,189.20
2021-01,YYC-NW,YYC-WH,24,881.49,837.42,11,10.75,24.49,118.25,269.39
2021-01,YYC-NW,YYC-WH,24,881.49,837.42,11,15.10,31.89,166.10,350.79
2021-01,YYC-NW,YYC-WH,24,881.49,837.42,14,14.35,28.58,200.90,400.12
2021-01,YYC-NW,YYC-WH,24,881.49,837.42,10,7.85,19.61,78.50,196.10
2021-01,YYC-SE,YYC-WH,23,765.47,727.20,4,8.09,18.92,32.36,75.68
2021-01,YYC-SE,YYC-WH,23,765.47,727.20,10,10.75,24.49,107.50,244.90
2021-01,YYC-SE,YYC-WH,23,765.47,727.20,5,15.10,31.89,75.50,159.45
2021-01,YYC-SE,YYC-WH,23,765.47,727.20,14,14.35,28.58,200.90,400.12
2021-01,YYC-SE,YYC-WH,23,765.47,727.20,6,7.85,19.61,47.10,117.66

In [ ]:
filter_mydata[['transactions', 'qty']].describe()

        transactions            qty
count  874892.000000  874892.000000
mean       34.017691      13.622753
std        24.319493       6.497370
min         5.000000       1.000000
25%        13.000000       9.000000
50%        27.000000      13.000000
75%        51.000000      17.000000
max       154.000000      46.000000

In [74]:
monthly_summary = filter_mydata.groupby(['date', 'store_id']).agg({
    'transactions': 'nunique',
    'revenue': 'sum',
    'qty': 'sum'
})

monthly_summary

                  transactions      revenue     qty
date    store_id
2021-01 YYC-DT              27   5925513.00   83328
        YYC-NW              26   4209052.00   56606
        YYC-SE              24   3530729.07   47430
2021-02 YYC-DT              26   6030640.00   88480
        YYC-NW              27   4221489.00   60872
...                        ...          ...     ...
2024-11 YYC-NW              31   7666356.00   87120
        YYC-SE              26   6498102.00   70560
2024-12 YYC-DT              38  13048647.00  161758
        YYC-NW              35   9220238.00  106888
        YYC-SE              32   7932835.00   87482

[144 rows x 3 columns]

In [46]:
## Stores as Columns
monthly_table = monthly_summary.pivot_table(index='date', columns='store_id', values=['transactions','revenue','qty'])
monthly_table.tail()

               qty                        revenue                        \
store_id    YYC-DT    YYC-NW   YYC-SE      YYC-DT     YYC-NW     YYC-SE
date
2024-08   112530.0   74648.0  63364.0   9391485.0  6608830.0  5646160.0
2024-09   106020.0   70020.0  56940.0   8883326.0  6396960.0  5361456.0
2024-10   116498.0   80352.0  65162.0   9682995.0  6973280.0  5843306.0
2024-11   129660.0   87120.0  70560.0  10705229.0  7666356.0  6498102.0
2024-12   161758.0  106888.0  87482.0  13048647.0  9220238.0  7932835.0

         transactions
store_id       YYC-DT    YYC-NW    YYC-SE
date
2024-08      291400.0  200600.0  177200.0
2024-09      274400.0  202100.0  163800.0
2024-10      294700.0  216600.0  174200.0
2024-11      337300.0  242400.0  196100.0
2024-12      406700.0  289800.0  251400.0

In [47]:
monthly_table.describe()

                    qty                                    revenue  \
store_id         YYC-DT         YYC-NW        YYC-SE        YYC-DT
count         48.000000      48.000000     48.000000  4.800000e+01
mean      112440.166667   73989.125000  61871.500000  8.644433e+06
std        18296.396891   11549.182518   9416.726481  1.480260e+06
min        80352.000000   52762.000000  45756.000000  5.925513e+06
25%       105136.500000   69285.000000  56918.500000  7.774491e+06
50%       110910.000000   72540.000000  61194.000000  8.530167e+06
75%       117707.000000   78712.500000  64650.500000  9.405294e+06
max       161758.000000  106888.000000  87482.000000  1.304865e+07

                                       transactions                 \
store_id        YYC-NW        YYC-SE         YYC-DT         YYC-NW
count     4.800000e+01  4.800000e+01      48.000000      48.000000
mean      6.136847e+06  5.200315e+06  268377.312500  191135.083333
std       1.065106e+06  9.127353e+05   45205.937855   34751.018385
min       4.209052e+06  3.530729e+06  178800.000000  132100.000000
25%       5.450806e+06  4.605841e+06  240550.000000  168950.000000
50%       6.093720e+06  5.142382e+06  263450.000000  189950.000000
75%       6.706161e+06  5.660967e+06  289125.000000  209175.000000
max       9.220238e+06  7.932835e+06  406700.000000  289800.000000


store_id         YYC-SE
count         48.000000
mean      160525.229167
std        28878.526411
min       108207.000000
25%       142241.250000
50%       160550.000000
75%       174375.000000
max       251400.000000

In [95]:
filter_mydata = filter_mydata.reset_index()

In [98]:
filter_mydata['units_sold'] = (filter_mydata['revenue']
                                / filter_mydata['unit_price']).round().astype(int)

In [99]:
store_check = filter_mydata.loc[
    (filter_mydata['date'] == '2021-01') &
    (filter_mydata['store_id'] == 'YYC-DT')
]

store_check.head()

,index,date,store_id,warehouse,transactions,revenue,net_revenue,qty,unit_cost,unit_price,total_cost,total_retail,units_sold
0,0,2021-01,YYC-DT,YYC-WH,31,1212.47,1151.85,20,8.09,18.92,161.8,378.40,64
1,1,2021-01,YYC-DT,YYC-WH,31,1212.47,1151.85,14,10.75,24.49,150.5,342.86,50
2,2,2021-01,YYC-DT,YYC-WH,31,1212.47,1151.85,16,15.10,31.89,241.6,510.24,38
3,3,2021-01,YYC-DT,YYC-WH,31,1212.47,1151.85,18,14.35,28.58,258.3,514.44,42
4,4,2021-01,YYC-DT,YYC-WH,31,1212.47,1151.85,10,7.85,19.61,78.5,196.10,62

In [87]:
filter_mydata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 874892 entries, 0 to 874891
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   date          874892 non-null  period[M]
 1   store_id      874892 non-null  object
 2   warehouse     874892 non-null  object
 3   transactions  874892 non-null  int64
 4   revenue       874892 non-null  float64
 5   net_revenue   874892 non-null  float64
 6   qty           874892 non-null  int64
 7   unit_cost     874892 non-null  float64
 8   unit_price    874892 non-null  float64
 9   total_cost    874892 non-null  float64
 10  total_retail  874892 non-null  float64
 11  units_sold    874892 non-null  float64
dtypes: float64(7), int64(2), object(2), period[M](1)
memory usage: 80.1+ MB

In [91]:


store_check = filter_mydata.loc[
    (filter_mydata['store_id'] == 'YYC-DT') & 
    (filter_mydata['date'] == '2021-01')
]

store_check

,date,store_id,warehouse,transactions,revenue,net_revenue,qty,unit_cost,unit_price,total_cost,total_retail,units_sold
0,2021-01,YYC-DT,YYC-WH,31,1212.47,1151.85,20,8.09,18.92,161.80,378.40,64.084038
1,2021-01,YYC-DT,YYC-WH,31,1212.47,1151.85,14,10.75,24.49,150.50,342.86,49.508779
2,2021-01,YYC-DT,YYC-WH,31,1212.47,1151.85,16,15.10,31.89,241.60,510.24,38.020383
3,2021-01,YYC-DT,YYC-WH,31,1212.47,1151.85,18,14.35,28.58,258.30,514.44,42.423723
4,2021-01,YYC-DT,YYC-WH,31,1212.47,1151.85,10,7.85,19.61,78.50,196.10,61.829169
...,...,...,...,...,...,...,...,...,...,...,...,...
18135,2021-01,YYC-DT,YYC-WH,18,603.81,573.62,15,15.10,27.51,226.50,412.65,21.948746
18136,2021-01,YYC-DT,YYC-WH,18,603.81,573.62,11,6.30,15.47,69.30,170.17,39.031028
18137,2021-01,YYC-DT,YYC-WH,18,603.81,573.62,25,6.27,11.51,156.75,287.75,52.459600
18138,2021-01,YYC-DT,YYC-WH,18,603.81,573.62,18,9.88,21.53,177.84,387.54,28.045053
18139,2021-01,YYC-DT,YYC-WH,18,603.81,573.62,15,11.86,27.23,177.90,408.45,22.174440

In [92]:
store_check['transactions'].unique()

array([31, 13, 36, 15, 37, 21, 45, 41, 20, 43, 16, 34, 19, 42, 17, 40, 22,
       47, 49, 14, 52, 50, 57, 35, 38, 18, 32])